source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'amecsummit' do
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  

  pod 'GoogleMaps'
end
